name: Generate Sensemaker report

on: workflow_dispatch

jobs:
  generate-summary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: "Jigsaw-Code/sensemaking-tools"
          path: sensemaking-tools

      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache-dependency-path: sensemaking-tools/package-lock.json
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm install
        working-directory: sensemaking-tools

      - name: Get CSV
        uses: valitydev/action-download-file@v1
        with:
          url: https://preprod.pol.is/api/v3/reportExport/r7kfpvrhdpyykbhnirtcd/comment-groups.csv
          target-path: sensemaking-tools/data/

      - name: List Files
        run: ls -l sensemaking-tools/
      
      - name: Generate Summary Output
        run: |
          npx ts-node runner-cli/runner.ts --outputFile "summary" \
          --vertexProject "jigsaw-vertex-integration" \
          --inputFile "data/comments.csv"
        working-directory: sensemaking-tools
